/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.chessgravity;


import it.unibo.chessgravity.controller.impl.ChessGravityObserverImpl;
import javafx.application.Application;

/** Main application entry-point's class. */

public final class Main {
    private Main() { }

    /**
     * Main application entry-point.
     * @param args
     */
    public static void main(final String[] args) {
        Application.launch(ChessGravityObserverImpl.class, args);
    }
}